// AUTO-GENERATED by scripts/gen-catalog.mjs - do not edit by hand.
// Authoring contract & pipeline: specs/document-api.md

export const NAV = [
 {
  "kind": "page",
  "title": "Home",
  "path": "/"
 },
 {
  "kind": "page",
  "title": "Knowledge graph",
  "path": "/graph"
 },
 {
  "kind": "page",
  "title": "Tracking calendar",
  "path": "/track"
 },
 {
  "kind": "group",
  "key": "g-example",
  "title": "示例",
  "children": [
   {
    "kind": "page",
    "title": "赛道首页",
    "path": "/example/"
   },
   {
    "kind": "page",
    "title": "Basics (example unit)",
    "path": "/example/unit-01-basics"
   },
   {
    "kind": "page",
    "title": "Node demo (example unit)",
    "path": "/example/unit-02-nodes"
   }
  ],
  "dir": "example"
 }
]

export const UNITS = [
 {
  "id": "ex-001",
  "title": "Basics (example unit)",
  "titles": {
   "en": "Basics (example unit)",
   "zh": "基础（示例单元）",
   "ja": "基本（サンプルユニット）"
  },
  "path": "/example/unit-01-basics",
  "course": "示例"
 },
 {
  "id": "ex-002",
  "title": "Node demo (example unit)",
  "titles": {
   "en": "Node demo (example unit)",
   "zh": "节点演示（示例单元）",
   "ja": "ノードのデモ（サンプルユニット）"
  },
  "path": "/example/unit-02-nodes",
  "course": "示例"
 }
]

export const PAGE_META = {
 "/": {
  "id": null,
  "created": "2026-09-09",
  "lang": "zh",
  "track": false,
  "title": "Home",
  "titles": null,
  "node": null
 },
 "/graph": {
  "id": "graph",
  "created": "2026-09-09",
  "lang": "zh",
  "track": false,
  "title": "Knowledge graph",
  "titles": null,
  "node": null
 },
 "/track": {
  "id": "track",
  "created": "2026-09-09",
  "lang": "zh",
  "track": false,
  "title": "Tracking calendar",
  "titles": null,
  "node": null
 },
 "/example/": {
  "id": null,
  "created": "2026-09-09",
  "lang": "zh",
  "track": false,
  "title": "Example",
  "titles": null,
  "node": null
 },
 "/example/unit-01-basics": {
  "id": "ex-001",
  "created": "2026-09-09",
  "lang": "multi",
  "track": true,
  "title": "Basics (example unit)",
  "titles": {
   "en": "Basics (example unit)",
   "zh": "基础（示例单元）",
   "ja": "基本（サンプルユニット）"
  },
  "node": null
 },
 "/example/unit-02-nodes": {
  "id": "ex-002",
  "created": "2026-09-09",
  "lang": "multi",
  "track": true,
  "title": "Node demo (example unit)",
  "titles": {
   "en": "Node demo (example unit)",
   "zh": "节点演示（示例单元）",
   "ja": "ノードのデモ（サンプルユニット）"
  },
  "node": {
   "mode": true,
   "prompt": null,
   "dims": [
    "pos",
    "topic"
   ]
  }
 }
}

export const NODE_SPEC = [
 {
  "path": "/example/unit-02-nodes",
  "id": "ex-002",
  "file": "example/unit-02-nodes.md",
  "mode": true,
  "prompt": null,
  "dims": [
   "pos",
   "topic"
  ]
 }
]
