// AUTO-GENERATED by scripts/gen-catalog.mjs - do not edit by hand.
// Authoring contract & pipeline: specs/document-api.md

export const NAV = [
 {
  "kind": "page",
  "title": "学习地图",
  "path": "/"
 },
 {
  "kind": "page",
  "title": "学习图谱",
  "path": "/graph"
 },
 {
  "kind": "page",
  "title": "追踪日历",
  "path": "/track"
 },
 {
  "kind": "group",
  "key": "g-english",
  "title": "英语",
  "children": [
   {
    "kind": "page",
    "title": "赛道首页",
    "path": "/english/"
   },
   {
    "kind": "group",
    "key": "g-english-vocab-core",
    "title": "词汇-核心",
    "children": [
     {
      "kind": "page",
      "title": "Unit 01 高频动词 12",
      "path": "/english/vocab-core/unit-01-core-verbs"
     },
     {
      "kind": "page",
      "title": "Unit 02 高频名词 12",
      "path": "/english/vocab-core/unit-02-core-nouns"
     },
     {
      "kind": "page",
      "title": "Unit 03 学习话题词",
      "path": "/english/vocab-core/unit-03-study-words"
     }
    ]
   },
   {
    "kind": "group",
    "key": "g-english-grammar-basics",
    "title": "基础语法",
    "children": [
     {
      "kind": "page",
      "title": "Unit 01 时态总览",
      "path": "/english/grammar-basics/unit-01-tenses"
     },
     {
      "kind": "page",
      "title": "Unit 02 句子成分",
      "path": "/english/grammar-basics/unit-02-sentence-parts"
     }
    ]
   }
  ]
 },
 {
  "kind": "group",
  "key": "g-math",
  "title": "数学",
  "children": [
   {
    "kind": "page",
    "title": "赛道首页",
    "path": "/math/"
   },
   {
    "kind": "page",
    "title": "Unit 01 心算加法",
    "path": "/math/unit-01-mental-addition"
   },
   {
    "kind": "page",
    "title": "Unit 02 分数速览",
    "path": "/math/unit-02-fractions-basics"
   }
  ]
 }
]

export const UNITS = [
 {
  "id": "e-gram-001",
  "title": "Unit 01 时态总览",
  "path": "/english/grammar-basics/unit-01-tenses",
  "course": "基础语法"
 },
 {
  "id": "e-gram-002",
  "title": "Unit 02 句子成分",
  "path": "/english/grammar-basics/unit-02-sentence-parts",
  "course": "基础语法"
 },
 {
  "id": "e-vocab-001",
  "title": "Unit 01 高频动词 12",
  "path": "/english/vocab-core/unit-01-core-verbs",
  "course": "词汇-核心"
 },
 {
  "id": "e-vocab-002",
  "title": "Unit 02 高频名词 12",
  "path": "/english/vocab-core/unit-02-core-nouns",
  "course": "词汇-核心"
 },
 {
  "id": "e-vocab-003",
  "title": "Unit 03 学习话题词",
  "path": "/english/vocab-core/unit-03-study-words",
  "course": "词汇-核心"
 },
 {
  "id": "m-001",
  "title": "Unit 01 心算加法",
  "path": "/math/unit-01-mental-addition",
  "course": "数学"
 },
 {
  "id": "m-002",
  "title": "Unit 02 分数速览",
  "path": "/math/unit-02-fractions-basics",
  "course": "数学"
 }
]

export const PAGE_META = {
 "/": {
  "id": null,
  "created": "2026-09-09",
  "lang": "zh",
  "track": false,
  "title": "学习地图",
  "node": null
 },
 "/graph": {
  "id": "graph",
  "created": "2026-09-09",
  "lang": "zh",
  "track": false,
  "title": "学习图谱",
  "node": null
 },
 "/track": {
  "id": "track",
  "created": "2026-09-09",
  "lang": "zh",
  "track": false,
  "title": "追踪日历",
  "node": null
 },
 "/english/": {
  "id": null,
  "created": "2026-09-09",
  "lang": "zh",
  "track": false,
  "title": "英语赛道",
  "node": null
 },
 "/english/vocab-core/unit-01-core-verbs": {
  "id": "e-vocab-001",
  "created": "2026-09-09",
  "lang": "zh",
  "track": true,
  "title": "Unit 01 高频动词 12",
  "node": {
   "mode": true,
   "prompt": null,
   "dims": [
    "词性",
    "主题"
   ]
  }
 },
 "/english/vocab-core/unit-02-core-nouns": {
  "id": "e-vocab-002",
  "created": "2026-09-09",
  "lang": "zh",
  "track": true,
  "title": "Unit 02 高频名词 12",
  "node": {
   "mode": true,
   "prompt": null,
   "dims": [
    "词性",
    "主题"
   ]
  }
 },
 "/english/vocab-core/unit-03-study-words": {
  "id": "e-vocab-003",
  "created": "2026-09-09",
  "lang": "zh",
  "track": true,
  "title": "Unit 03 学习话题词",
  "node": null
 },
 "/english/grammar-basics/unit-01-tenses": {
  "id": "e-gram-001",
  "created": "2026-09-09",
  "lang": "zh",
  "track": true,
  "title": "Unit 01 时态总览",
  "node": null
 },
 "/english/grammar-basics/unit-02-sentence-parts": {
  "id": "e-gram-002",
  "created": "2026-09-09",
  "lang": "zh",
  "track": true,
  "title": "Unit 02 句子成分",
  "node": null
 },
 "/math/": {
  "id": null,
  "created": "2026-09-09",
  "lang": "zh",
  "track": false,
  "title": "数学赛道",
  "node": null
 },
 "/math/unit-01-mental-addition": {
  "id": "m-001",
  "created": "2026-09-09",
  "lang": "zh",
  "track": true,
  "title": "Unit 01 心算加法",
  "node": {
   "mode": true,
   "prompt": "unit-01-mental-addition.prompt.md",
   "dims": [
    "题型",
    "技巧"
   ]
  }
 },
 "/math/unit-02-fractions-basics": {
  "id": "m-002",
  "created": "2026-09-09",
  "lang": "zh",
  "track": true,
  "title": "Unit 02 分数速览",
  "node": null
 }
}

export const NODE_SPEC = [
 {
  "path": "/english/vocab-core/unit-01-core-verbs",
  "id": "e-vocab-001",
  "file": "english/vocab-core/unit-01-core-verbs.md",
  "mode": true,
  "prompt": null,
  "dims": [
   "词性",
   "主题"
  ]
 },
 {
  "path": "/english/vocab-core/unit-02-core-nouns",
  "id": "e-vocab-002",
  "file": "english/vocab-core/unit-02-core-nouns.md",
  "mode": true,
  "prompt": null,
  "dims": [
   "词性",
   "主题"
  ]
 },
 {
  "path": "/math/unit-01-mental-addition",
  "id": "m-001",
  "file": "math/unit-01-mental-addition.md",
  "mode": true,
  "prompt": "unit-01-mental-addition.prompt.md",
  "dims": [
   "题型",
   "技巧"
  ]
 }
]
