// Nav hub: NAV/UNITS/PAGE_META are AUTO-GENERATED by scripts/gen-catalog.mjs
// (source of truth = markdown files under site/, see specs/document-api.md).
import { NAV as GEN_NAV, UNITS as GEN_UNITS, PAGE_META as GEN_META, NODE_SPEC as GEN_NODE_SPEC } from './catalog.gen'

export interface NavPage { kind: 'page'; title: string; path: string }
export interface NavGroup { kind: 'group'; key: string; title: string; children: NavNode[] }
export type NavNode = NavPage | NavGroup

export const NAV = GEN_NAV as NavNode[]
export const UNITS = GEN_UNITS as { id: string; title: string; path: string; course: string }[]
export const PAGE_META = GEN_META as Record<string, {
  id: string | null; created: string | null; lang: string | null; track: boolean; title: string
  node: { mode: boolean; prompt: string | null; dims: string[] | null } | null
}>
export const NODE_SPEC = GEN_NODE_SPEC

export const MK_TREE_EXPANDED_KEY = 'mk.tree.expanded'
